import { Providers } from "./providers";
import '../styles/globals.css'
import { Montserrat } from 'next/font/google'
import Banner from '../components/banner/Banner'
const montserrat = Montserrat({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='sr'>
      <head>
      </head>
      <body className={montserrat.className}>
        <Providers>
          <Banner />
          {children}
        </Providers>
      </body>
    </html>
  )
}
